[SERV-400] Add OAuth Token Utility
UCLALibrary/libcal-proxy pull request #1
Opened 2022-05-02 21:17 UTC by DRickard

Add code and test to application to retrieve an OAuth bearer token from LibCal.
* Create TokenUtils class
* Create TokenUtilsTest unit test
* Add useful constants to Config and JsonKeys
* Add environment variables to pom

2022-05-03 21:13 UTC, markmatney requested changes
I am still waiting to receive admin API credentials for LibCal, so am not able to run the test at the moment. However, when I run the build locally, I do see that PMD fails (and Checkstyle too, I assume), which should be fixed.

2022-05-03 21:27 UTC, markmatney commented
Update: I have just received credentials and am able to get the tests to pass. 👍🏻

2022-05-03 23:36 UTC, DRickard commented
> 

Pushed style and PMD fixes

2022-05-04 17:01 UTC, ksclarke approved these changes

2022-05-04 19:05 UTC, markmatney approved these changes

2022-05-04 20:21 UTC, merged